import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionProvider from "./SessionProvider";
import ReduxProvider from "./ReduxProvider";
// import { motion, AnimatePresence } from "framer-motion"; // No longer directly used in app router layout

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <SessionProvider>
            {/* In Next.js 13+ App Router, AnimatePresence is typically used within individual page/component transitions
            rather than the root layout. For root layout transitions, you would need a more complex setup
            or a different approach. For now, just render children directly. */}
            {children}
          </SessionProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
